### ISSUE TITLE
Build for diffrents architecture

### ISSUE THREAD

**Issue by corentin-wedge** [FlorianREGAZ/Python-Tls-Client#1]
I have a problem loading the .so file, i'm on a mac m1.

**Comment by FlorianREGAZ** [comment]
Hey Corentin, 

do you have Discord for faster communication, if so I please send me your tag? I don't have a M1 Mac, so I can't really test it myself sadly.

**Comment by corentincc** [comment]
Add me : MichelRebel#4821

**Comment by FlorianREGAZ** [comment]
Should be fixed with newest update! :)
