### ISSUE TITLE
Updating shared libraries

### ISSUE THREAD

**Issue by fakeastap** [FlorianREGAZ/Python-Tls-Client#100]
Hello!
 @FlorianREGAZ  Are you going to update the shared libs? They have added support for ECH. 

 https://github.com/bogdanfinn/tls-client/releases/tag/v1.7.1

**Comment by FlorianREGAZ** [comment]
will be updated in next version

**Comment by AmericanY** [comment]
@FlorianREGAZ is it possible to reach you via DM?
