### ISSUE TITLE
Segmentation fault on Mac (Catalina 10.15.7)

### ISSUE THREAD

**Issue by papachef08** [FlorianREGAZ/Python-Tls-Client#17]
... the error occurs directly at where the library is loaded:
library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')

File exists and filepath is ok. 
Obtain: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Selected file is: tls-client-x86.dylib

Running with:
Python 3.10.8

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/35

**Comment by papachef08** [comment]
Update to BigSur may be a workaround, but not a real fix. Can you open source the tls-client-x86.dylib or where did you get it from? (It may also be a security issue, if we use closed sourced libs from anywhere providing with our password ...)

**Comment by acheong08** [comment]
@papachef08
It's taken from https://github.com/bogdanfinn/tls-client

**Comment by acheong08** [comment]
The dist is taken directly from there

**Comment by papachef08** [comment]
... good to know. There are updated versions of the libs in https://github.com/bogdanfinn/tls-client, however the error still remains. I opened an issue there.

**Comment by FlorianREGAZ** [comment]
Could you guys please try with the latest version?

**Comment by peterschwps** [comment]
@FlorianREGAZ I'm still getting it unfortunately
