### ISSUE TITLE
Question about Custom Example

### ISSUE THREAD

**Issue by FuckingToasters** [FlorianREGAZ/Python-Tls-Client#18]
I am wondering if it is required to change the other settings on the custom example shown on the readme when the ja3 string is changed or if they can be kept the same. I'm not quite sure keeping them the same make the requests look sus or not.

If i need to change the values depending on the ja3 string, how would i be able to do this?

**Comment by FlorianREGAZ** [comment]
In order to make the fingerprint look realistic, you'll probably have to update other values if you change the ja3. Thats correct. :)

**Comment by FuckingToasters** [comment]
> In order to make the fingerprint look realistic, you'll probably have to update other values if you change the ja3. Thats correct. :)

okay so i can't just take a random ja3 from a file of ja3's? in which way would i need to change the other values based on the ja3 string?
