### ISSUE TITLE
can't compile with Nuitka

### ISSUE THREAD

**Issue by TrixTM** [FlorianREGAZ/Python-Tls-Client#21]
It gives this error:
FileNotFoundError: Could not find module 'C:\Users\TrixTM\Desktop\GENV10~2\GENSER~1.DIS\tls_client\dependencies\tls-client.dll' (or one of its dependencies). Try using the full path with constructor syntax.

How can i include the dll?

**Comment by FlorianREGAZ** [comment]
Hey, the dll got renamed to `tls-client-64.dll` and `tls-client-32.dll`

**Comment by TrixTM** [comment]
main.py
`import tls_client
session = tls_client.Session(
    client_identifier="chrome_108"
)
res = session.get(
    "https://httpbin.org/get",
    headers={
        "trixtm": "true",
    }
)
print(res.text)
input()
`
nuitka command:
nuitka --standalone --follow-imports --include-data-files=C:/Users/xCrysti/AppData/Local/Programs/Python/Python39\Lib/site-packages/tls_client/dependencies/tls-client-64.dll=tls-client-64.dll main.py

And i get this error: FileNotFoundError: Could not find module 'C:\Users\xCrysti\Desktop\TLSTES~1\MAIN~1.DIS\tls_client\dependencies\tls-client-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

So i include the dll but it still can't find it

**Comment by kekeds** [comment]
SKIDDD

**Comment by Hydroxzz** [comment]
SKIDD
