### ISSUE TITLE
Auto Redirect

### ISSUE THREAD

**Issue by dev7machine** [FlorianREGAZ/Python-Tls-Client#29]
Is there auto redirect flag for tls_client?

**Comment by gbe3hunna** [comment]
As stated in the execute_request method parameters, you can use **allow_redirects** which is False by default: 

`def execute_request(
        self,
        method: str,
        url: str,
        params: Optional[dict] = None,  # Optional[dict[str, str]]
        data: Optional[Union[str, dict]] = None,
        headers: Optional[dict] = None,  # Optional[dict[str, str]]
        cookies: Optional[dict] = None,  # Optional[dict[str, str]]
        json: Optional[dict] = None,  # Optional[dict]
        allow_redirects: Optional[bool] = False,
        insecure_skip_verify: Optional[bool] = False,
        timeout_seconds: Optional[int] = 30,
        proxy: Optional[dict] = None  # Optional[dict[str, str]]
    ): `

**Comment by dev7machine** [comment]
Thanks.
