### ISSUE TITLE
cookie issues

### ISSUE THREAD

**Issue by Dario24K** [FlorianREGAZ/Python-Tls-Client#38]
I am trying to reproduce a get request stream and I noticed that duplicate cookies are being sent, I don't know if I did something wrong, but every time I find the usual cookies with key, value and domain two times

**Comment by andreaWtraining** [comment]
I get the same error, cookies are duplicated it's like if cookie jar doesn't replace old cookies with the new ones

**Comment by FlorianREGAZ** [comment]
This should be fixed with the newest update. :)

**Comment by DaBossCoda** [comment]
Im still getting double cookies :/
