### ISSUE TITLE
Custom TLS Fingerprints aren't working

### ISSUE THREAD

**Issue by JFuqX** [FlorianREGAZ/Python-Tls-Client#4]
Hi i just wanted to submit, that custom fingerprints aren't working.
With presets everything is working fine.

I am on MacOS with M1 and on the recent version of your package.

I thought I did something wrong but even with your custom example I get the following error:

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client/sessions.py", line 334, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tls_client/sessions.py", line 317, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://tls.peet.ws/api/all": unknown extension with id 27 provided

**Comment by FlorianREGAZ** [comment]
Hey JFuqX,

could you send me a code snippet with which I can replicate the error please?

**Comment by FlorianREGAZ** [comment]
Could you try the latest version please? The code snippet you send me works for me. 
If it still doesn't work, please let me know. I'll try to get my hands on a Mac then.

**Comment by JFuqX** [comment]
Everthing works now!

Again thank you for this awesome contribution!
