### ISSUE TITLE
tls_client.exceptions.TLSClientExeption: failed to do request||| unknown extension with id 22 provided

### ISSUE THREAD

**Issue by louissiu198** [FlorianREGAZ/Python-Tls-Client#60]
tls_client.exceptions.TLSClientExeption: failed to do request||| unknown extension with id 22 provided
i 'got this error with tls client 
for session.post
        session = tls_client.Session(
            #client_identifier="chrome110",
            ja3_string=self.getJA3(headers),
            h2_settings={"HEADER_TABLE_SIZE": 65536,"MAX_CONCURRENT_STREAMS": 1000,"INITIAL_WINDOW_SIZE": 6291456,"MAX_HEADER_LIST_SIZE": 262144},
            h2_settings_order=["HEADER_TABLE_SIZE","MAX_CONCURRENT_STREAMS","INITIAL_WINDOW_SIZE","MAX_HEADER_LIST_SIZE"],
            supported_signature_algorithms=["ECDSAWithP256AndSHA256","PSSWithSHA256","PKCS1WithSHA256","ECDSAWithP384AndSHA384","PSSWithSHA384","PKCS1WithSHA384","PSSWithSHA512","PKCS1WithSHA512",],
            supported_versions=["GREASE", "1.3", "1.2"],
            key_share_curves=["GREASE", "X25519"],
            cert_compression_algo="brotli",
            connection_flow=15663105
        )
        response = session.post(
            url="",
            headers=headers,
            proxy="")

**Comment by tvg6u56bu5i** [comment]
how to fix thx

**Comment by louissiu198** [comment]
i fixed it lmafo i thought my self so dumb
