### ISSUE TITLE
Support streaming response

### ISSUE THREAD

**Issue by xtekky** [FlorianREGAZ/Python-Tls-Client#62]
Is accepting a streaming response already implemented ? 
It would be nice being able to use something like:
```python
response = requests.get('https://example.com/stream', stream=True)
for chunk in response.iter_content(chunk_size=1024)
    print(chunk)
```

**Comment by ading2210** [comment]
@xtekky By the way did you ever get streaming to work with this library? I see you've marked it as resolved.

**Comment by acheong08** [comment]
Streaming works by writing to a temporary file

**Comment by acheong08** [comment]
Using a different but similar library: 
- https://github.com/acheong08/ChatGPT/pull/1382
