### ISSUE TITLE
请求网页乱码

### ISSUE THREAD

**Issue by jxhczhl** [FlorianREGAZ/Python-Tls-Client#74]
url = 'https://book.citilink.co.id/LoginAgency.aspx'

`
session = tls_client.Session(
    client_identifier="chrome112",
    random_tls_extension_order=True
)

response = session.get(url, params=params, headers=headers)

print(response.text)
`
get请求这个网页，返回不正确的内容(乱码)

![image](https://github.com/FlorianREGAZ/Python-Tls-Client/assets/41224971/4e51578a-dfe7-4a0d-ba29-7ced80a1b1ed)

**Comment by mciem** [comment]
true

**Comment by jxhczhl** [comment]
在go版本的tls-client issue中找到了回答，设置请求头就行了
