### ISSUE TITLE
Is there a way not to show traceback?

### ISSUE THREAD

**Issue by MsLolita** [FlorianREGAZ/Python-Tls-Client#9]
It takes to much space in console, can I turn off it?
![image](https://user-images.githubusercontent.com/58307006/202583609-d0b0adaa-4777-4f41-a7d4-5a4dff59da32.png)

**Comment by FlorianREGAZ** [comment]
Hey, could you send me an example please to replicate the bug?

**Comment by MsLolita** [comment]
Sorry I can't but as I see it is simple timeout error when site proxy/site didn't responde some time.
net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Get "https://api-v2.rtfkt.com/api/users/address": write tcp 192.167.2.112:51943->54.204.232.160:31112: i/o timeout

**Comment by FlorianREGAZ** [comment]
Not sure if this is exactly what you mean, but you can catch the errors. 
Here is an example:

```python
from tls_client.exceptions import TLSClientExeption
import tls_client

session = tls_client.Session(
    client_identifier="chrome_107"
)

try:
    res = session.get(
        "http://www.google.com:81/",
        timeout_seconds=1
    )
except TLSClientExeption as e:
    print(f"TLS Client Error: {e}")
```

**Comment by Tkd-Alex** [comment]
> Sorry I can't but as I see it is simple timeout error when site proxy/site didn't responde some time.
> net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> Get "https://api-v2.rtfkt.com/api/users/address": write tcp 192.167.2.112:51943->54.204.232.160:31112: i/o timeout

I've a similar issue, sometimes with the proxies I get randomly i/o timeout

**Comment by MsLolita** [comment]
> > Sorry I can't but as I see it is simple timeout error when site proxy/site didn't responde some time.
> > net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> > Get "https://api-v2.rtfkt.com/api/users/address": write tcp 192.167.2.112:51943->54.204.232.160:31112: i/o timeout
> 
> I've a similar issue, sometimes with the proxies I get randomly i/o timeout

I'm not sure, but this seems to have solved my problem https://github.com/FlorianREGAZ/Python-Tls-Client/issues/9#issuecomment-1320968519

**Comment by Tkd-Alex** [comment]
> > > Sorry I can't but as I see it is simple timeout error when site proxy/site didn't responde some time.
> > > net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> > > Get "https://api-v2.rtfkt.com/api/users/address": write tcp 192.167.2.112:51943->54.204.232.160:31112: i/o timeout
> > 
> > I've a similar issue, sometimes with the proxies I get randomly i/o timeout
> 
> I'm not sure, but this seems to have solved my problem https://github.com/FlorianREGAZ/Python-Tls-Client/issues/9#issuecomment-1320968519

The **timeout** or the **try exception**?

**Comment by Tkd-Alex** [comment]
> > ```python
> > TLSClientExeption 
> > ```
> 
> I mean catching TLSClientExeption error. It doesn't show any extra logs

Ok thank you, but the timeout issue persist at this point 😔 I got randomly tcp i/o timeout with proxies, also with a huge timeout value
